import { BeerPost, BreweryPost } from './types';

export const MOCK_BEERS: BeerPost[] = [
  {
    id: 1,
    name: 'La Bionda',
    brewery: 'Birrificio del Ducato',
    nation: 'Italia',
    type: 'Golden Ale',
    abv: 5.0,
    price: 6.00,
    imageUrl: 'https://images.unsplash.com/photo-1618885450690-435b86fb3a53?q=80&w=1964&auto=format&fit=crop',
    ratings: [{ user_id: '1', value: 4 }, { user_id: '2', value: 5 }],
    comments: [],
    description: 'Una birra dal colore dorato brillante, con schiuma fine e persistente. Al naso emergono profumi di agrumi e fiori bianchi.',
    user_id: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Re Ale Extra',
    brewery: 'Birra del Borgo',
    nation: 'Italia',
    type: 'American Pale Ale',
    abv: 6.4,
    price: 6.50,
    imageUrl: 'https://images.unsplash.com/photo-1587883984633-c3444a733735?q=80&w=1974&auto=format&fit=crop',
    ratings: [{ user_id: '1', value: 5 }],
    comments: [],
    description: 'Una APA con un\'esplosione di luppoli americani. Note di pompelmo, resina e frutta tropicale dominano il profilo aromatico.',
    user_id: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Isaac',
    brewery: 'Baladin',
    nation: 'Italia',
    type: 'Blanche',
    abv: 5.0,
    price: 5.80,
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?q=80&w=1974&auto=format&fit=crop',
    ratings: [{ user_id: '1', value: 4 }, { user_id: '2', value: 4 }, { user_id: '3', value: 5 }],
    comments: [],
    description: 'Birra bianca elegante, speziata con coriandolo e scorza d\'arancia amara. Fresca, dissetante e molto beverina.',
    user_id: 'system',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_BREWERIES: BreweryPost[] = [
  {
    id: 101,
    name: 'Birrificio Lambrate',
    address: 'Via Adelchi, 5',
    city: 'Milano',
    nation: 'Italia',
    lat: 45.4800,
    lng: 9.2200,
    imageUrl: 'https://images.unsplash.com/photo-1556910110-a5a63dfd9904?q=80&w=2070&auto=format&fit=crop',
    ratings: [{ user_id: '1', value: 5 }, { user_id: '2', value: 5 }],
    comments: [],
    description: 'Storico birrificio milanese, pioniere della birra artigianale in Italia. Atmosfera unica e birre indimenticabili.',
    user_id: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 102,
    name: 'Ma Che Siete Venuti a Fa\'',
    address: 'Via di Benedetta, 25',
    city: 'Roma',
    nation: 'Italia',
    lat: 41.8902,
    lng: 12.4683,
    imageUrl: 'https://images.unsplash.com/photo-1594404339398-3199a5a3a005?q=80&w=2070&auto=format&fit=crop',
    ratings: [{ user_id: '1', value: 5 }, { user_id: '2', value: 4 }],
    comments: [],
    description: 'Un pub leggendario nel cuore di Trastevere, con una selezione di birre artigianali da tutto il mondo che fa girare la testa.',
    user_id: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 103,
    name: 'Open Baladin',
    address: 'Via degli Specchi, 6',
    city: 'Roma',
    nation: 'Italia',
    lat: 41.8954,
    lng: 12.4722,
    imageUrl: 'https://images.unsplash.com/photo-1621939512592-3ab79a8f5724?q=80&w=2070&auto=format&fit=crop',
    ratings: [{ user_id: '1', value: 4 }],
    comments: [],
    description: 'Il tempio della birra Baladin a Roma. Un locale moderno con un\'offerta vastissima di birre alla spina e in bottiglia, e un menu food da abbinare.',
    user_id: 'system',
    created_at: new Date().toISOString(),
  },
];
